# client-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: scd-project
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
