apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: scd-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: username/client:latest
          ports:
            - containerPort: 3000
