apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: scd-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: username/server:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "<your-mongodb-uri>"
