apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: scd-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ibbitibbi/server:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URL
              value: "mongodb+srv://ibbitibbi400:test@test.xsclqhe.mongodb.net/?retryWrites=true&w=majority&appName=test"