apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: scd-project
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002